# Basic Configuration
CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n

#==============================================================================
# Custom Configurations
#==============================================================================
# These settings are user-defined and can be adjusted for each device.

# Sensor and BLE Advertising Settings
CONFIG_SENSOR_SLEEP_DURATION_SEC=300
CONFIG_BLE_ADV_USE_CODED_PHY=n
CONFIG_BLE_ADV_DURATION_SEC=5
CONFIG_BLE_DFU_ADV_DURATION_SEC=60
CONFIG_BLE_MIN_ADV_INTERVAL_MS=30
CONFIG_BLE_MAX_ADV_INTERVAL_MS=40
CONFIG_BLE_USER_DEFINED_MAC_ADDR="f0:ca:f0:ca:01:e8" # Change this for each device
CONFIG_BLE_USER_DEFINED_NAME="LRIMa 67" # Change this for each device

# Sensor Sleep Modification 
CONFIG_SENSOR_SLEEP_MODIFICATION_ENABLED=y
# NOTA : The following five parameters are only used if CONFIG_SENSOR_SLEEP_MODIFICATION_ENABLED=y
CONFIG_SENSOR_SLEEP_DURATION_MAX_SEC=3600
# BLE Connection Settings
CONFIG_BLE_CONN_TIMEOUT_SEC=60

#==============================================================================
# Logging Configuration
#==============================================================================
CONFIG_LOG=n
CONFIG_DEBUG_OPTIMIZATIONS=n

# Logging Backends
CONFIG_MAIN_LOG_LEVEL_INF=n
CONFIG_AHT20_LOG_LEVEL_WRN=n
CONFIG_SHT20_LOG_LEVEL_WRN=n
CONFIG_SHT31_LOG_LEVEL_WRN=n
CONFIG_SHT4X_LOG_LEVEL_WRN=n
CONFIG_STCC4_LOG_LEVEL_WRN=n
CONFIG_ADC_LOG_LEVEL_DBG=n
CONFIG_BLE_DRIVER_LOG_LEVEL_DBG=n
CONFIG_BUTTON_LOG_LEVEL_WRN=n
CONFIG_LED_LOG_LEVEL_WRN=n

# Support for log
CONFIG_PICOLIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=n

#==============================================================================
# Bluetooth Configuration
#==============================================================================
CONFIG_BT=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_CTLR_PHY_CODED=n
CONFIG_BT_EXT_ADV_MAX_ADV_SET=2
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_GATT_CLIENT=n
CONFIG_BT_GATT_DM=n
CONFIG_BT_GATT_DYNAMIC_DB=n
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
CONFIG_BT_SMP=y
CONFIG_BT_SMP_SC_PAIR_ONLY=y

#==============================================================================
# Over the Air Update Configuration
#==============================================================================
CONFIG_ZCBOR=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_MCUMGR=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=n
CONFIG_MCUMGR_MGMT_NOTIFICATION_HOOKS=y
CONFIG_MCUMGR_SMP_COMMAND_STATUS_HOOKS=y
CONFIG_BT_L2CAP_TX_MTU=252
CONFIG_BT_BUF_ACL_RX_SIZE=256
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

#==============================================================================
# Size Optimization and Multithreading
#==============================================================================
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_MULTITHREADING=y
CONFIG_REBOOT=y

#==============================================================================